# Generated by Django 6.0.1 on 2026-03-19 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('destination', models.CharField(max_length=200)),
                ('out_date', models.DateField()),
                ('out_time', models.TimeField()),
                ('return_date', models.DateField()),
                ('return_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending Parent Approval'), ('parent_approved', 'Parent Approved'), ('parent_rejected', 'Parent Rejected'), ('warden_approved', 'Warden Approved'), ('warden_rejected', 'Warden Rejected'), ('checked_out', 'Checked Out'), ('returned', 'Returned')], default='pending', max_length=30)),
                ('parent_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('parent_approved_at', models.DateTimeField(blank=True, null=True)),
                ('parent_remarks', models.TextField(blank=True)),
                ('warden_approved_at', models.DateTimeField(blank=True, null=True)),
                ('warden_remarks', models.TextField(blank=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('qr_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outing_requests', to=settings.AUTH_USER_MODEL)),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outing_approvals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
